### ISSUE TITLE
How to read geojson?

### ISSUE THREAD

**Issue by divyselva** [duckdb/duckdb_spatial#101]
Is there a way to read in a csv of geojsons --> and convert geometry column with geometry dictionary {type, coordinates} into a polygon? 

using `read_json_auto(file, format=newline_delimited)` data looks like this; 
![Screenshot 2023-07-13 at 2 22 12 PM](https://github.com/duckdblabs/duckdb_spatial/assets/58446818/717b9ca8-edf5-4f88-9931-12c771d41a0e)

**Comment by marklit** [comment]
Have a look at https://github.com/duckdblabs/duckdb_spatial/issues/12

**Comment by Maxxen** [comment]
Implemented in #91 and take a look at the tests there for example usage.
