### ISSUE TITLE
what is ST_Envelope_Agg ?

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb_spatial#139]
The [web docs](https://duckdb.org/docs/extensions/spatial.html#spatial-aggregate-functions) mention aggregation functions including `ST_Envelope_Agg` (which shows a :duck: native implementation).  How is this defined?  I don't see it in the GitHub README either.  I'd be very interested in aggregation functions.

**Comment by Maxxen** [comment]
Sorry about that, we're working on updating the docs and the readme here on GitHub properly. 

The ST_Envelope_Agg basically returns a bounding box (as a polygon) containing the bounding box of all the input geometries. The signature is `GEOMETRY ST_Extent_Agg(GEOMETRY)`. The source is [here](https://github.com/duckdblabs/duckdb_spatial/blob/main/spatial/src/spatial/core/functions/aggregate/st_envelope_agg.cpp)

**Comment by Maxxen** [comment]
Hmm, come to think of it it should probably be changed/aliased to `ST_Extent`, like in [PostGIS](http://www.postgis.net/docs/ST_Extent.html)
