### ISSUE TITLE
Add ST_MakeEnvelope function

### ISSUE THREAD

**Issue by ttomasz** [duckdb/duckdb_spatial#143]
It would be nice to have a simple way to define bbox e.g. for filtering. In Postgis I usually used [ST_MakeEnvelope](https://postgis.net/docs/ST_MakeEnvelope.html)  which as far as I can tell has not been implemented here.

**Comment by Maxxen** [comment]
HI! Thanks for opening this issue! I agree that a ST_MakeEnvelope function would be nice, but for now you should be able to workaround it by doing a cast from the BOX_2D type.

```sql
SELECT {min_x: 10, min_y: 10, max_x: 20, max_y: 20 }::BOX_2D::GEOMETRY;
```
