### ISSUE TITLE
Suspected bug on Debian/Ubuntu when exporting to Shapefile

### ISSUE THREAD

**Issue by felix-schott** [duckdb/duckdb_spatial#144]
Hi there,

Thanks for working on this amazing tool!

I would like to report a suspected bug that occurs on Debian/Ubuntu when exporting a table to Shapefile. 

Please have a look at [this repo](https://github.com/felix-schott/duckdb-spatial-bug) which should give you enough information to reproduce the error. We noticed the bug in a test pipeline, it seems to happen on debian and ubuntu but not on Pop OS. 
If this is not a bug but a problem with the environment, I'd equally be grateful for guidance.

Thanks
Felix

**Comment by Maxxen** [comment]
Hi! Thanks for the amazingly detailed reproducible steps! I suspect it might already be solved by #145, but I'm going to check out the example repo and take a more detailed look at this tomorrow!

**Comment by Maxxen** [comment]
Ok, seems like this was indeed fixed. For now you can grab the latest version where this is fixed from the CI https://github.com/duckdb/duckdb_spatial/actions/runs/6537910123 (if you scroll down a bit to under Artifacts there are updated builds suffixed with -0.9.1)

**Comment by felix-schott** [comment]
Thanks a lot @Maxxen!

**Comment by giswqs** [comment]
I have been scratching my head why I keep getting the `Bad file descriptor` when trying to exporting data to shapefile format until I found this issue. It occurs on my Manjaro/Arch Linux. Glad to hear that it has been resloved. 

Just curious when the new version will be released/

**Comment by Maxxen** [comment]
Hey! @giswqs @felix-schott  We just got development builds for spatial working, so you should be able to install the latest spatial version for duckdb v0.9.1 by executing:
```
FORCE INSTALL spatial FROM 'http://nightly-extensions.duckdb.org';
```
