### ISSUE TITLE
Add `ST_LineMerge` function from GEOS

### ISSUE THREAD

**Issue by RaczeQ** [duckdb/duckdb_spatial#147]
While building a native OSM reader, every existing implementation I have found relies on the `ST_LineMerge` or `linemerge` function that is imported from GEOS. Since GEOS is already in the extension, maybe it won't be a huge problem to add it (even with mapping from native LINESTRING_2D to GEOS object first).

For now, I have utilized the python function registering, but this won't be as fast as the native function.

And on a similar topic, do you know how can I split the `MultiLineString` into the list of `LineStrings`? `ST_NGeometries` returns a value 5, but I don't know where to go from here without another python function and iterating over geoms. The same question probably applies to `MultiPoints` and `MultiPolygons`.
Edit: I have found the `ST_GeometryN` function in PostGIS that allows for the extraction of subgeoms. So maybe it's another function to add to `duckdb`?

```python
from shapely import wkt as shp_wkt
from typing import List, cast
from shapely.ops import linemerge
import duckdb

connection = duckdb.connect(config=dict(allow_unsigned_extensions=True))
connection.install_extension('spatial') # loading from github action artifact
connection.load_extension('spatial')

def _linemerge_shapely(wkt_strings: List[str]) -> str:
    linestrings = [shp_wkt.loads(wkt_string) for wkt_string in wkt_strings]
    merged_linestring = linemerge(linestrings)
    merged_linestring_wkt = cast(str, merged_linestring.wkt)
    return merged_linestring_wkt

connection.create_function(
    "py_linemerge_shapely",
    _linemerge_shapely,
    [duckdb.list_type(type=duckdb.typing.VARCHAR)],
    duckdb.typing.VARCHAR,
)

duckdb_linemerge_macro_query = """
CREATE OR REPLACE MACRO ST_LineMerge(geometries) AS 
ST_GeomFromText(py_linemerge_shapely([ST_AsText(g) for g in geometries]));
"""
connection.execute(duckdb_linemerge_macro_query)

connection.sql('''
SELECT ST_LineMerge([
    ST_GeomFromText('LINESTRING (0 0, 1 1)'),
    ST_GeomFromText('LINESTRING (0 0, 0 1)'),
    ST_GeomFromText('LINESTRING (0 1, 1 1)'),
    ST_GeomFromText('LINESTRING (1 1, 1 0)'),
    ST_GeomFromText('LINESTRING (1 0, 0 0)'),
    ST_GeomFromText('LINESTRING (5 5, 6 6)'),
    ST_GeomFromText('LINESTRING (1 1, 100 100)'),
]) as merged_lines
''')

┌────────────────────────────────────────────────────────────────────────────────────────────┐
│                                        merged_lines                                        │
│                                          geometry                                          │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│ MULTILINESTRING ((1 1, 1 0, 0 0), (0 0, 1 1), (0 0, 0 1, 1 1), (1 1, 100 100), (5 5, 6 6)) │
└────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Maxxen** [comment]
Hello! Thanks for raising this issue!

I agree that ST_LineMerge along with other constructive aggregates like ST_Polygonize would be nice to expose since those are some of the really valuable operations provided by GEOS.  I'll look into it. 

To split the geometrycollection, it looks like we would need something like [ST_Dump](https://postgis.net/docs/ST_Dump.html). Its shouldn't be too hard to implement, its just the `path` return-value that's slightly annoying, but we could return it as part of a `STRUCT`.
