### ISSUE TITLE
ST_READ is incredibly slow when working with files in S3 (via httpfs extension)

### ISSUE THREAD

**Issue by jdoig** [duckdb/duckdb_spatial#148]
Querying a small (4.4mb) shz file locally is very fast!
Querying the same file via the httpfs file plugin is **incredibly** slow.

* duckdb is performing amazingly well when querying much larger, non-spatial, data from S3.
* My connection speeds are fine and the s3 file in question downloads in a fraction of a second.

**Comment by Maxxen** [comment]
Hi! Are you querying shapefiles? I think there is an optional part of the filesystem layer that we haven't implemented yet which may be the cause of this slowdown. Is it equally slow if you query through [GDALs remote filesystem](https://gdal.org/user/virtual_file_systems.html#network-based-file-systems) (/vsicurl/ or /vsis3/) instead, e.g. using `st_read('/vsicurl/www.someurl.com/some/path.shp')`

We've realized that there are other issues with plugging DuckDBs filesystem into GDAL and it doesn't seem like there is a good way to solve them properly right now, so we might just revert some of the changes in #126. You will still be able to query remote files though by using the `/vsi/` prefix though, but not through `httpfs`.

**Comment by jdoig** [comment]
Thanks @Maxxen . it's a `.shz` (shapefile zip).
`/vsis3/` does work but the initial call is just as slow as via `httpfs` (though subsequent queries are not all as slow as the initial query, like they are using `httpfs`)

**Comment by Maxxen** [comment]
If `/vsis3/` is slow too then there is not much we can do unfortunately, it's probably just hard to read a compressed file without doing a lot of seeking, which gets expensive when done remotely.

**Comment by jdoig** [comment]
Thanks, it's slightly lower than geopandas for reading this file remotely, but not enough for me to want to give up on all the other perks of using duckdb.
