### ISSUE TITLE
ST_Intersects & ST_Intersection error

### ISSUE THREAD

**Issue by jjcfrancisco** [duckdb/duckdb_spatial#152]
I am trying to find geometries that intersect with other geometries but duckdb fails. This is the query in question:

```sql
SELECT r.* FROM countries c, rivers r WHERE ST_Intersects(c.geom, r.geom);
```

I get the following error:
`Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.`
`Original error: "INTERNAL Error: Failed to bind column reference "geom" [0.0] (bindings: [1.0 1.1 1.2])"`

I get similar/same error with `ST_Intersection` -> https://postgis.net/docs/ST_Intersection.html

Interestingly enough, if I use the following (ugly) query, there is **no** error and I get the resulting geometries:
```sql
SELECT ST_Intersects(c.geom, r.geom) ic, r.geom FROM countries c, rivers r WHERE ic = TRUE;
```

Seems linked to the `WHERE` clause?

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue. It looks like some of the rewrite-rules introduced in #128 cause invalid bindings. I'm looking into it!

**Comment by Maxxen** [comment]
Hey! This should now be fixed since #154, but we also just got development builds for spatial working, so you can install the latest spatial version where this is fixed for duckdb v0.9.1 by executing:
```sql
FORCE INSTALL spatial FROM 'http://nightly-extensions.duckdb.org';
```

**Comment by Maxxen** [comment]
Please let me know if you run into more binding errors!

**Comment by jjcfrancisco** [comment]
Thanks for the reply @Maxxen & speedy action 🙏
