### ISSUE TITLE
doc problem

### ISSUE THREAD

**Issue by tpolong** [duckdb/duckdb_spatial#159]
These functions(st_distance_spheroid ,st_distance_within_spheroid,st_length_spheroid,st_area_spheroid    ,st_perimeter_spheroid) lack documentation, and the documentation(st_buffer) for this function is incorrect,lack of parameter and parameter explanation..

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue!
I'm aware that the documentation is very outdated at this point. I have some ideas on how to refactor the way we produce and provide documentation for the spatial extension that I want to get working on soon. I'll leave this issue open until we've fixed it.

**Comment by tpolong** [comment]
您好，您的邮件已收到，谢谢！
