### ISSUE TITLE
Compile source code error. 

### ISSUE THREAD

**Issue by cuteDen-ECNU** [duckdb/duckdb_spatial#163]
Hi! When I compile the source code, I encounter this issue:

/script/duckdb_spatial/spatial/src/spatial/core/functions/table/st_read_osm.cpp:94:16: error: could not convert 'result' from 'unique_ptr<spatial::core::BindData,default_delete<spatial::core::BindData>,[...]>' to 'unique_ptr<duckdb::FunctionData,default_delete<duckdb::FunctionData>,[...]>'
   94 |         return result;
      |                ^~~~~~
      |                |
      |                unique_ptr<spatial::core::BindData,default_delete<spatial::core::BindData>,[...]>

My Cmake version is 3.22 that is newer than 3.20:
```
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
And My g++ version is 12.3, the newest version that can be accessed using a package manager. 
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 12.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-12-ALHxjy/gcc-12-12.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-12-ALHxjy/gcc-12-12.3.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~22.04) 
```

**Comment by Maxxen** [comment]
Hmm, strange that CI hasnt caught this. We need to insert an std::move before the return. I can push a fix soon.

**Comment by cuteDen-ECNU** [comment]
Thank you very much!

**Comment by Maxxen** [comment]
Thanks for reporting this issue! It should now be fixed in #164

**Comment by cuteDen-ECNU** [comment]
It could be missed. 🤔
/script/duckdb_spatial/spatial/src/spatial/core/functions/table/st_read_osm.cpp:255:16: error: could not convert 'global_state' from 'unique_ptr<spatial::core::GlobalState,default_delete<spatial::core::GlobalState>,[...]>' to 'unique_ptr<duckdb::GlobalTableFunctionState,default_delete<duckdb::GlobalTableFunctionState>,[...]>'
  255 |         return global_state;
      |                ^~~~~~~~~~~~
      |                |
      |                unique_ptr<spatial::core::GlobalState,default_delete<spatial::core::GlobalState>,[...]>

**Comment by Maxxen** [comment]
Yeah, seems like I missed some other spots. This is only a problem on older version of GCC due to DuckDB implementing its own unique_ptr class, so I can't test it easily locally. Ill try to fix the rest of the occurrences in the next PR I make (soon hopefully)

**Comment by cuteDen-ECNU** [comment]
> This is only a problem on older version of GCC due to DuckDB implementing its own unique_ptr class

Which the gcc and g++ versions you are using? Mine is 12.3.0.
gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~22.04)

**Comment by Maxxen** [comment]
Im using Clang :) - but I think I fixed some more stuff in the latest push, does it work now? Otherwise ill set up a VM and try myself.

**Comment by cuteDen-ECNU** [comment]
Successfully compile it using clang. ^^ Thanks for the clarification.
