### ISSUE TITLE
Assertion failed in InteriorPointPoint

### ISSUE THREAD

**Issue by cuteDen-ECNU** [duckdb/duckdb_spatial#176]
This statement crashes the debug version of the DuckDB Spatial extension:
```sql
SELECT ST_PointOnSurface(g)  FROM (SELECT ST_GeomFromText('MULTIPOINT((0 0), EMPTY)') As g);
```
The assertion failed here:
```
duckdb: /duckdb_spatial/build/debug/deps/projects/Source/GEOS/src/algorithm/InteriorPointPoint.cpp:68: void geos::algorithm::InteriorPointPoint::add(const geos::geom::CoordinateXY*): Assertion `point' failed.
```

Version:
```
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.9.2-dev209   │ 6545a55cfe │
└─────────────────┴────────────┘
```
The assertion failure is triggered using the latest nightly version of the Spatial extension.

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue! Maybe next time you [could link me directly to where it was fixed](https://github.com/libgeos/geos/pull/977) or reference the GitHub discussion when you're the owner of the original GEOS issue so I don't accidentally open new issue in GEOS or spend time on my own fix.

I'll see if I can update our GEOS bundle to latest main later this week.

**Comment by cuteDen-ECNU** [comment]
Sorry for missing the original issue link.
Next time I will attach it.

**Comment by cuteDen-ECNU** [comment]
To follow up on this, we did not know in advance that both of these test cases triggered the same underlying bug. We are currently developing an automated testing tool for testing spatial databases, and independently found test cases that crash PostGIS and DuckDB. Sorry again!

**Comment by cuteDen-ECNU** [comment]
I'm just checking whether an update is planned, so I could potentially report more issues. I would greatly appreciate this, but can understand that this might not be a high priority for you.

**Comment by Maxxen** [comment]
Im updating GEOS in #193 which should contain fixes for all the issues you found so far, but please feel free to report more issues (unless this is blocking) and I'll try fix them as soon as I can!
