### ISSUE TITLE
Crash when joining using ST_WITHIN (Internal Error: Failed to bind column reference [...])

### ISSUE THREAD

**Issue by adrivn** [duckdb/duckdb_spatial#177]
DuckDB v0.9.1
Spatial Extension v0.9.1

Upon a simple join using ST_Within, it returns the error `Error: INTERNAL Error: Failed to bind column reference "asset_location" [0.0] (bindings: [1.0 1.1])`

The query used was:
`D select a.*, s.municipality from placesofinterest a join postal_sections s on st_within(a.place_location, s.area_gmaps);`

However, when querying using raw input and the WHERE clause, it appears to work:

`D select * from postal_sections where st_within(st_point(42.795606, 0.6479754), area_gmaps);`

Should you need additional debug output, please let me know.

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue! I think this has been fixed in #154, could you try to see if it still occurs if you install the latest beta version of the spatial extension? You can get it by executing: `FORCE INSTALL spatial FROM 'http://nightly-extensions.duckdb.org';`

**Comment by adrivn** [comment]
It works now. Thank you for the prompt response. I will close this now, as I assume this will ship with the next stable release.
