### ISSUE TITLE
st_transform not working properly

### ISSUE THREAD

**Issue by giswqs** [duckdb/duckdb_spatial#179]
I tried to convert a geometry column from `EPSG:4326` to other CRS (e.g., `EPSG:5070`) and got an `Invalid latititue` error.  I am pretty sure the latitude values are valid. Is this a bug?

```python
import duckdb

con = duckdb.connect()
con.install_extension("httpfs")
con.load_extension("httpfs")
con.install_extension("spatial")
con.load_extension("spatial")

url = 'https://open.gishub.org/data/duckdb/cities.parquet'
con.sql(f"SELECT * EXCLUDE geometry, ST_GeomFromWKB(geometry) AS geometry FROM '{url}'")
```
![image](https://github.com/duckdb/duckdb_spatial/assets/5016453/3cccf04c-ae02-4266-809a-19b727b67098)

```python
con.sql(f"SELECT * EXCLUDE geometry, st_transform(ST_GeomFromWKB(geometry), 'EPSG:4326', 'EPSG:5070') AS geometry FROM '{url}'")
```
![image](https://github.com/duckdb/duckdb_spatial/assets/5016453/e99294c8-853b-4c67-a294-6e96773a74af)

**Comment by jc9677** [comment]
I had this issue a couple of months ago. I believe PROJ is misinterpreting the coordinate pair ordering. See https://github.com/duckdb/duckdb_spatial/issues/119

I just tried your example and passed 'true' for the optional `always_xy` parameter of ST_Transform, and it worked for me:

`con.sql(f"SELECT * EXCLUDE geometry, st_astext(st_transform(ST_GeomFromWKB(geometry), 'EPSG:4326', 'EPSG:5070', true)) AS geometry FROM '{url}'")`

<img width="1134" alt="Screenshot 2023-11-11 at 10 10 26 PM" src="https://github.com/duckdb/duckdb_spatial/assets/65202162/a4239388-76c9-42c9-85e1-2f5b13128c45">

**Comment by jc9677** [comment]
@Maxxen - Is it bad etiquette for me to chime in with a possible solution before the repo owner? I have no idea!

**Comment by giswqs** [comment]
@jc9677 Thank you for providing the solution. I had no idea that the `ST_Transform` function has a `always_xy` parameter. The duckdb spatial documentation only shows the first three parameters, and the repo home page example also does not use the `always_xy` either. It would be great if the DuckDB API reference has detailed information about each spatial function. 
```
GEOMETRY ST_Transform(GEOMETRY, VARCHAR, VARCHAR)
```

Chiming in with a possible solution before the repo owner is actually appreciated. As a maintainer myself, I love seeing users chime in and help others. It saves the maintainer's time.
