### ISSUE TITLE
Install SPATIAL Error

### ISSUE THREAD

**Issue by diehl** [duckdb/duckdb_spatial#190]
Just installed DuckDB v0.9.2 via Homebrew on my Mac and attempted to install the Spatial extension via the CLI.
Seeing the following:

```
D install SPATIAL;
Error: HTTP Error: Failed to download extension "SPATIAL" at URL "http://extensions.duckdb.org/v0.9.2/osx_arm64/SPATIAL.duckdb_extension.gz"
```

Going to the URL above, I'm seeing:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>Y5ESN48E183S7ZZE</RequestId>
<HostId>yCrKLaIStgH5ailBSDeyy3zm6d0q7HMRwmxBceLwcgl+4DQw950hCwhFcj9cCX2aif+cUQm97Go=</HostId>
</Error>
```

**Comment by Maxxen** [comment]
Hi! It seems like extension names are case sensitive in the `INSTALL` command. e.g. it seems to be available on: http://extensions.duckdb.org/v0.9.2/osx_arm64/spatial.duckdb_extension.gz

Could you try running this instead?: 
```sql
INSTALL spatial; 
LOAD spatial
```

**Comment by diehl** [comment]
Hi @Maxxen ! 

I'm seeing the following but I'm suspecting it is due to my attempt last night to use the 0.9.1 extension that I downloaded and installed. Is there a way for me to uninstall that and try again with the 0.9.2 extension you referenced above?

```
D INSTALL spatial;
D LOAD spatial;
Error: Invalid Input Error: Extension "/Users/cpd/.duckdb/extensions/v0.9.2/osx_arm64/spatial.duckdb_extension" version (v0.9.1) does not match DuckDB version (v0.9.2)
```

I downloaded the 0.9.2 extension and did the following which didn't change anything.
```
D INSTALL 'spatial.duckdb_extension';
D LOAD spatial;
Error: Invalid Input Error: Extension "/Users/cpd/.duckdb/extensions/v0.9.2/osx_arm64/spatial.duckdb_extension" version (v0.9.1) does not match DuckDB version (v0.9.2)
```

I also tried a `brew uninstall duckdb` and `brew install duckdb` but it still seems to have awareness of the extension.

**Comment by Maxxen** [comment]
Extensions are stored in your duckdb home directory (~/.duckdb/), but I thunk you can also force a reinstall with:

`FORCE INSTALL spatial`

**Comment by diehl** [comment]
Turned out I needed to delete the `extensions/` directory. `FORCE INSTALL` didn't do the trick on its own. But thankfully I've got it successfully installed now. Appreciate your prompt replies @Maxxen! Thank you!

**Comment by mtravis** [comment]
I'm seeing a similar issue with python

```
con.install_extension("spatial")

HTTPException: HTTP Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.9.2/linux_arm64_gcc4/spatial.duckdb_extension.gz"
Extension "spatial" is an existing extension.

```

**Comment by Maxxen** [comment]
Hi! As of now, we don't support linux_arm64_gcc4. In the future we may though.
