### ISSUE TITLE
NotImplementedException: Not implemented Error: Data type 'geometry' not recognized

### ISSUE THREAD

**Issue by carlsunderman** [duckdb/duckdb_spatial#212]
When getting data from a geopandas dataframe, I will receive an error "Data type 'geometry' not recognized". 

Is this expected behavior?

To reproduce this issue, I downloaded a Rivers shapefile from https://datacatalog.worldbank.org/search/dataset/0042032/Major-Rivers-of-the-World.

```
import duckdb
import geopandas as gpd
con = duckdb.connect()
con.sql('INSTALL spatial; LOAD spatial')
gdf = gpd.read_file("C:/RiversShapefile.zip")
# Tried both method below with the same error
#x = con.sql("select * from gdf")
x = con.sql("select * exclude geometry, ST_AsText(geometry) as geom from gdf")
```

Now I know that some people may say that duckdb can read shapefiles, but supporting geometry types from geopandas could be useful

**Comment by Maxxen** [comment]
Yes, this is currently expected behavior. There is no special geopandas interoperability yet. In theory it should not be that complicated, but the issue is that DuckDB lacks a mechanism for registering custom python type conversions in extensions.

**Comment by carlsunderman** [comment]
@Maxxen yes, it's not a roadblock and I think we may have discussed this before, I can't recall, but thought I would just doublecheck
