### ISSUE TITLE
Exporting excel to s3 is not working 

### ISSUE THREAD

**Issue by osalloum** [duckdb/duckdb_spatial#218]
I am trying to export an excel file into s3 via GDAL
however we are getting this error 

libc++abi: terminating due to uncaught exception of type duckdb::IOException: IO Error: GDAL Error (3): Cannot create s3://some-bucket-eu-west-1/xxxx/output.xlsx: s3://some-bucket-eu-west-1/xxx/output.xlsx: Undefined error: 0

This is what I am running

call load_aws_credentials();
install spatial;
load spatial;
copy ( select 1 as a , 2 as b ) to 's3://some-bucket-eu-west-1/xxx/output.xlsx' WITH (FORMAT GDAL, DRIVER 'xlsx');

**Comment by Maxxen** [comment]
Hi! Thanks for filing this issue!
Do you have the `httpfs` extension loaded as well?

**Comment by osalloum** [comment]
I just tried with explicitly loading the httpfs extension but it did not help 

call load_aws_credentials();
install httpfs;
load httpfs;
install spatial;
load spatial;
 copy ( select 1 as a , 2 as b ) to 's3://some-bucket-eu-west-1/xxx/output.xlsx' WITH (FORMAT GDAL, DRIVER 'xlsx');

**Comment by Maxxen** [comment]
I think this maybe have been fixed on main. You can get the latest spatial version built from the latest merged PR in this repository with all recent fixes and features for DuckDB v0.9.2 using

```
FORCE INSTALL spatial FROM 'http://nightly-extensions.duckdb.org';
```

**Comment by osalloum** [comment]
Indeed, it is working fine on the nightly

**Comment by Maxxen** [comment]
Cool! Ill go ahead and close this then!
