### ISSUE TITLE
different value of `ST_Distance` depending on value of `always_xy`in `ST_Transform`

### ISSUE THREAD

**Issue by ncclementi** [duckdb/duckdb_spatial#219]
Data:  https://s3.amazonaws.com/tripdata/202003-citibike-tripdata.csv.zip

```sql
load spatial;

CREATE TABLE biketrip AS SELECT * , st_transform(st_point("start station latitude", "start station longitude"), 'EPSG:4326', 'EPSG:3857') pickup_point,  st_transform(st_point("end station latitude", "end station longitude"), 'EPSG:4326', 'EPSG:3857') dropoff_point FROM '202003-citibike-tripdata.csv';

Explore trip patterns by user type
SELECT
    usertype,
    AVG(tripduration) AS avg_duration,
    AVG(ST_Distance(pickup_point, dropoff_point)) AS avg_distance
FROM
    biketrip
GROUP BY
    usertype;
```
This returns avg_distance : 
Subscribers: 2457.47758 
Customer: 3017.728121

While if we do:
```sql
load spatial;

CREATE TABLE biketrip AS SELECT * , st_transform(st_point("start station latitude", "start station longitude"), 'EPSG:4326', 'EPSG:3857', true) pickup_point,  st_transform(st_point("end station latitude", "end station longitude"), 'EPSG:4326', 'EPSG:3857', true) dropoff_point FROM '202003-citibike-tripdata.csv';

Explore trip patterns by user type
SELECT
    usertype,
    AVG(tripduration) AS avg_duration,
    AVG(ST_Distance(pickup_point, dropoff_point)) AS avg_distance
FROM
    biketrip
GROUP BY
    usertype;
```

I think this is a bug in `ST_Transform` because the distance seems to be computed correctly. Moreover, when using `always_xy=True` the transformation matches with geopandas. Meaning that the problem is most likely in the default implementation of `st_transform`. 

Geopandas transformation example:
```python
import geopandas as gpd
import pandas as pd

df = pd.read_csv('202003-citibike-tripdata.csv')
pickup_points = gpd.points_from_xy(df['start station latitude'], df['start station longitude'])
pickup_points.crs = 'EPSG:4326'
pickup_points.to_crs('EPSG:3857')
```

The points returned after this operation, match with 
```sql
st_transform(st_point("start station latitude", "start station longitude"), 'EPSG:4326', 'EPSG:3857', true) pickup_point
```

**Comment by Maxxen** [comment]
With just having a cursory glance at this, is this not expected? You are passing latitude/longitude in both cases, even when `always_xy = true` where it should be lon/lat. IIRC geopandas always does the equivalent of `always_xy := true` by default which is why you get a different result when you don't use it.

`ST_Distance` does not take the projection into account, it just does a cartesian distance calculation.

**Comment by ncclementi** [comment]
I think we definitely misunderstood on our end what this parameter does, but after some thought I think now we do? please confirm if this is the right interpretation for duckdb implementation: 

- Output is always in x, y format
- The assume input (with default value `always_xy=False`) is lat/long which is equivalent to y, x
- If the user is providing input data as lon/lat they need to pass `always_xy=True`

**Comment by Maxxen** [comment]
Well yes, but it also depends on the projection parameters you pass in. I think the big source of confusion is that wgs84 (epsg 4326) is standardized to be in lat/lon (even though almost all gis systems ignore that and pretend its always lon/lat), while basically every other projection youd care about is in lon/lat.

**Comment by ncclementi** [comment]
Thanks @Maxxen this is very helpful. Closing this.

**Comment by Maxxen** [comment]
For what its worth we will probably change this at some point to be consistent with the rest of the ecosystem, see eg #63
