### ISSUE TITLE
`st_area` result mismatch with PostGIS 3.3 for SRID other than 4326 and 4087

### ISSUE THREAD

**Issue by ludovicgayet-aviv** [duckdb/duckdb_spatial#222]
Hello,

_First a big thanks for all the effort you put in this extension, really appreciated._

I have issues when i try to compute `ST_area` **on different SRID. It seems that duck provide wrong result when the SRID is different than 4326 and 4087.**

I'm running duckdb `0.9.2`
I compared the result with `Postgis (3.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1)`

Here is a minimal reproductible example :

Postgis : 

```
WITH create_geom AS (
    SELECT ST_SetSRID(ST_GeomFromText('POLYGON ((-82.03623 29.60482, -82.0357 29.605, -82.03526 29.60513, -82.03623 29.60482))'), 4326) as geom_4326
)
SELECT
    ST_AREA(geom_4326) as area_4326,
    ST_AREA(st_transform(geom_4326,'EPSG:3857')) as area_3857,
    ST_AREA(st_transform(geom_4326,'EPSG:4087')) as area_4087,
    ST_AREA(st_transform(geom_4326,'EPSG:3035')) as area_3035
FROM create_geom;
```

DuckDB :
```
import duckdb

geom = 'POLYGON ((-82.03623 29.60482, -82.0357 29.605, -82.03526 29.60513, -82.03623 29.60482))'
duckdb.sql("INSTALL spatial;LOAD spatial;")

duckdb.sql(
    f"""
    WITH create_geom AS (
        SELECT
            ST_GeomFromText('{geom}') as geom_4326
    )
    SELECT
        ST_AREA(ST_TRANSFORM(geom_4326, 'EPSG:4326', 'EPSG:4326')) as area_geo_4326,
        ST_AREA(ST_TRANSFORM(geom_4326, 'EPSG:4326', 'EPSG:3857')) as area_geo_3857,
        ST_AREA(ST_TRANSFORM(geom_4326, 'EPSG:4326', 'EPSG:4087')) as area_geo_4087,
        ST_AREA(ST_TRANSFORM(geom_4326, 'EPSG:4326', 'EPSG:3035')) as area_geo_3035,
    FROM create_geom
    """
).show()
```

Postgis Results : 

![Capture d’écran 2023-12-29 à 12 11 10](https://github.com/duckdb/duckdb_spatial/assets/138591891/9a0abc1c-a10d-410f-b194-80013e39a2b2)

Duckdb Results:
````
┌────────────────────────┬──────────────────┬───────────────────┬──────────────────┐
│     area_geo_4326      │  area_geo_3857   │   area_geo_4087   │  area_geo_3035   │
│         double         │      double      │      double       │      double      │
├────────────────────────┼──────────────────┼───────────────────┼──────────────────┤
│ 5.1500000016351076e-09 │ 460.401158770248 │ 63.81894951745801 │ 8.90960380835827 │
└────────────────────────┴──────────────────┴───────────────────┴──────────────────┘
````

The example i used here is a small area extracted from your test but i encountered this bug while using big geom like countries, regions.

Thanks for the help

**Comment by Maxxen** [comment]
Hi! Thanks for reportibg this issue. By just taking a quick glance at this I suspect this is due to the axis order of the different projections. wgs84 (epsg 4326) is standardized to be in lat/lon even though most GIS systems (including postgis) ignores this and always assume geometries to be in lon/lat regardless of what the crs mandates. DuckDB tries to be neutral with this which is a common source of confusion. We will probably change this to be in line with postgis in the future.

You can try passing either flipping the coordinates with st_flipcoordinates or passing "always_xy := true" in st_transform.

See eg #219 #215 #179 #63
