### ISSUE TITLE
st_area_spheroid - strange behaviour for polygons with holes

### ISSUE THREAD

**Issue by EvgeniyPaskin** [duckdb/duckdb_spatial#224]
I'm using ST_Area_Spheroid to get area of polygons (landplots) in square meters. It does the work with 2 issues:
1. Minor issue: The area comes as negative value (but correct in absolute)
2. Major issue: The area of the polygon with a hole in it is calculated incorrectly (looks like the hole is not substracted).

I've checked the data with PostGIS and GeoPandas which were consistent in correct hole substraction

If I'm doing smt wrong - would appreciate any suggestions to the mistakes made. 
If any workaround exist within DuckDB - I would very much prefer to stay with DuckDB (migrating my workflow from PostGIS/GeoPandas)

```SQL
COPY (
    SELECT
        st_flipcoordinates(st_transform(geom,'EPSG:3857', 'EPSG:4326')) AS geometry,
        st_area_spheroid((st_transform(geom,'EPSG:3857', 'EPSG:4326'))) AS AREA_CALC_DUCKDB
        FROM rr_geo.rr_geo_raw 
) TO 'test_export.geojson'
WITH (FORMAT GDAL, DRIVER 'GeoJSON', LAYER_CREATION_OPTIONS 'WRITE_BBOX=YES');
```
To confirm my suspicions I've used the following GeoPandas procedure:
```Python
import geopandas as gpd
gdf = gpd.read_file("test_export.geojson")
gdf["area_gpd"] = gdf["geometry"].to_crs({'proj':'cea'}).area
gdf
```
Resulting in the following DataFrame:
![Screenshot from 2024-01-07 17-09-18](https://github.com/duckdb/duckdb_spatial/assets/20067572/c1594fea-0a66-42e6-9d8d-a7eb62a137bd)

For reference: Polygons look as follows
![Screenshot from 2024-01-07 17-10-01](https://github.com/duckdb/duckdb_spatial/assets/20067572/0fc57626-ba22-44a2-a9b8-f4edd51a4eda)

The GeoJSON file attached (extension changed due to github limitation)
[test_export.geojson.json](https://github.com/duckdb/duckdb_spatial/files/13854132/test_export.geojson.json)

**Comment by Maxxen** [comment]
Hi! Thanks for filing this issue! 
This does indeed seem like a problem on our end. Im working on a fix.
