### ISSUE TITLE
Export to excel fails with `GDAL Error (1): File extension should be XLSX` when file exists.

### ISSUE THREAD

**Issue by michael-simons** [duckdb/duckdb_spatial#231]
```
INSTALL spatial;
LOAD spatial;

create table tbl (x varchar(200));
insert into tbl values('hallo');
-- straight from the docs
COPY tbl TO 'output.xlsx' WITH (FORMAT GDAL, DRIVER 'xlsx');
```

>  Error: IO Error: GDAL Error (1): File extension should be XLSX

```
duckdb -version
v0.9.2 3c695d7ba9

macOS, 14.1.1 (23B81), m1
```

**Comment by michael-simons** [comment]
Ok, this is the error message when the file already exists… It is stated in the docs that the file must not exists, but you would never assume that to be the cause reading the message.

Changed the title of this issue.

**Comment by Maxxen** [comment]
Hi! Thanks for filing this issue. Seems like this is an underlying issue with the GDAL driver, or perhaps with how it interacts with our filesystem abstraction. It may very well be possible that we can improve this error message somehow.

**Comment by michael-simons** [comment]
Thanks for the detailed and understandable write-up. I can relate and agree.
