### ISSUE TITLE
ST_Read fails on GeoJSON data with 3D coordinates

### ISSUE THREAD

**Issue by jheer** [duckdb/duckdb_spatial#244]
Some GeoJSON files may include 3D points -- geometries whose coordinates can contain 3 dimensions. This is a valid part of the [GeoJSON specification](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1). Here's one example of this in the wild, from the USGS: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson

At first glance, it looks like this is supported by GDAL (though to be fair I did not look very deep):
- https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/geojson/ogrgeojsonreader.h#L84
- https://github.com/OSGeo/gdal/blob/master/ogr/ogrpoint.cpp#L81

However, trying to read such a file with the `spatial` extension fails. If you run the following in DuckDB v0.9.2:

```sql
INSTALL spatial;
LOAD spatial;
CREATE TABLE quakes AS SELECT *
FROM ST_READ('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson')
```

The result is:

```
Error: Not implemented Error: Geometry type '1001' not supported
```

Even if DuckDB `spatial` does not support points other than Point2D, it would be useful to be able to parse the first two coordinates (e.g., lat/lon) rather than fail with an error. Thanks!

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue. Thankfully this is already fixed in #226

**Comment by jheer** [comment]
Thanks!! I would love to see this addition and we'd make good use of it in the [Mosaic project](https://uwdata.github.io/mosaic/).

**Comment by Maxxen** [comment]
DuckDB Spatial now supports coordinates with Z and M values properly, so this is now possible without information loss!
