### ISSUE TITLE
How to set more than one LAYER_CREATION_OPTIONS?

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb_spatial#245]
Hi,
if apply this command to natural earth data

```
duckdb -c "copy (select POSTAL,geom from st_read('./data/ne_110m_admin_0_countries.shp')) TO 'tmp.geojson' WITH (FORMAT GDAL, DRIVER 'GeoJSON', LAYER_CREATION_OPTIONS 'WRITE_BBOX=YES',LAYER_CREATION_OPTIONS 'RFC7946=YES')"
```

I have this error

```
Error: Parser Error: Unexpected duplicate option "LAYER_CREATION_OPTIONS"
```

How to set more than one LAYER_CREATION_OPTIONS?

Thank you

**Comment by Maxxen** [comment]
You can pass a list ov VARCHARs, e.g `["key1=val1", "key2=val2"]`

**Comment by aborruso** [comment]
> You can pass a list ov VARCHARs, e.g `["key1=val1", "key2=val2"]`

I have tried

```
duckdb -c "COPY (SELECT w.*, n.* FROM st_read('./output/world.geojson') w LEFT JOIN read_csv_auto('./output/nazionalita_2023.csv') n ON w.POSTAL = n.\"ISO_3166-1\" ORDER BY POSTAL) TO 'tmp.geojson' WITH (FORMAT GDAL, DRIVER 'GeoJSON', LAYER_CREATION_OPTIONS \"['WRITE_BBOX'='YES','RFC7946'='YES']\")"
```

And I have

```
Error: Not implemented Error: GDAL Error (6): dataset tmp.geojson does not support layer creation option ['WRITE_BBOX'
```

Thank you

**Comment by Maxxen** [comment]
Dont pass the list inside quotes, DuckDB supports list literals natively.

**Comment by aborruso** [comment]
> Dont pass the list inside quotes, DuckDB supports list literals natively.

I have change it in `LAYER_CREATION_OPTIONS ['WRITE_BBOX'='YES','RFC7946'='YES']` and now I have

```
Error: Parser Error: syntax error at or near "["
LINE 1: ...IVER 'GeoJSON', LAYER_CREATION_OPTIONS ['WRITE_BBOX'='YES','RFC7946'='YES'])
```

**Comment by Maxxen** [comment]
Try: `LAYER_CREATION_OPTIONS ["WRITE_BBOX=YES","RFC7946=YES"] `

**Comment by Maxxen** [comment]
Nevermind, this is broken. You used to be able to do this but I think the binding logic has changed in DuckDB so that it's no longer possible. 

I will work on a fix soon.

**Comment by Maxxen** [comment]
Nevermind, I always forget the copy-to syntax is different, sorry, this is how you do it, you pass the list as a parenthesis:
```
... WITH (FORMAT 'GDAL', DRIVER 'GeoJSON', LAYER_CREATION_OPTIONS ('WRITE_BBOX=YES', 'RFC7946=YES'), SRS 'EPSG:4326');
```

**Comment by aborruso** [comment]
It works, thank you very much
