### ISSUE TITLE
Create a GeoParquet file: is there a related duckdb way to create properly it?

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb_spatial#251]
Hi, 
if I understand correctly, if I run

```
duckdb -c "COPY (SELECT * from st_read('input.shp')) TO 'tmp.parquet' WITH (FORMAT PARQUET)"
```

I do not have a GeoParquet file. But I can use [gpq](https://github.com/planetlabs/gpq) to convert the output parquet to GeoParquet.

But in the metadata of the GeoParquet I do not have info about the coordinate reference system:

```json
"metadata": {
    "version": "",
    "primary_column": "geometry",
    "columns": {
      "geometry": {
        "encoding": "WKB",
        "geometry_types": [
          "Polygon",
          "MultiPolygon"
        ],
        "bbox": [
          313279.2514000004,
          3933846.2156000007,
          1312016.1506000003,
          5220292.292199999
        ]
      }
    }
  }
```

How to complete a right creation of geoparquet, starting from duckdb, and create an output that has also a CRS associated to it?

Thank you

**Comment by Maxxen** [comment]
Not yet, but will hopefully be possible next release.

You also need to convert the geometry to WKB when saving it to parquet if you want to be able to open it in other programs.

**Comment by aborruso** [comment]
> You also need to convert the geometry to WKB when saving it to parquet if you want to be able to open it in other programs.

In my example I use gpq, and it converts the geometry to WKB. The only thing missing is the ability to associate a coordinate system.

**Comment by Youssef-Harby** [comment]
Hi @aborruso .. I made a workaround, you can check this : https://colab.research.google.com/drive/1c2MSiktw3Ahuu3RChFOS-tcdlPG4cHT1?usp=sharing
