### ISSUE TITLE
DuckDB 0.10 GDAL virtual file systems IO Error

### ISSUE THREAD

**Issue by mick** [duckdb/duckdb_spatial#255]
Great to see the DuckDB 0.10 release today! Lots of great things in that release, but I wanted to flag an issue using [GDAL virtual file systems.](https://gdal.org/user/virtual_file_systems.html)

In 0.10, both relative and absolute paths using `/vsigzip/` failed to load.

```
❯ duckdb
v0.10.0 20b1486d11
D install spatial;
D load spatial;
D select * from st_read('/vsigzip/data/la-census-tracts.geojson.gz');
Error: IO Error: GDAL Error (4): Failed to open file /vsigzip/data/la-census-tracts.geojson.gz: {"exception_type":"IO","exception_message":"Cannot open file \"/vsigzip/data/la-census-tracts.geojson.gz\": No such file or directory","errno":"2"}
```

In earlier duckdb versions this works as expected: 

```
❯ duckdb
v0.9.2 3c695d7ba9
D load spatial;
D select * from st_read('/vsigzip/data/la-census-tracts.geojson.gz');
... data table preview...
```

DuckDB Spatial has been super great to use, thanks for all the work on this!

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue! I haven't had the time to look into this yet but I wouldn't be surprised if this broke after all the work on the filesystem abstractions that has taken place during this release cycle. 
I'll try to have a proper look later this week!

**Comment by ncclementi** [comment]
@mick This error used to show up for me when not having the `httpfs` extension loaded. Can you check this is not the same than this https://github.com/duckdb/duckdb_spatial/issues/210#issuecomment-1850927552

**Comment by mick** [comment]
```
❯ duckdb10
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install httpfs;
D load httpfs;
D install spatial;
D load spatial;
D select * from st_read('/vsigzip/data/la-census-tracts.geojson.gz');
Error: IO Error: GDAL Error (4): Failed to open file /vsigzip/data/la-census-tracts.geojson.gz: {"exception_type":"IO","exception_message":"Cannot open file \"/vsigzip/data/la-census-tracts.geojson.gz\": No such file or directory","errno":"2"}
```

@ncclementi Thanks for the suggestion, and the issue does sound related to similar filesystem abstraction changes that impacted #210. 

Looking around a bit, here is what I think is happening: the filesystem change to [add a `/vsiduckdb-<uuid>/` client_prefix](https://github.com/Maxxen/duckdb_spatial/blob/00495b9c68852e616743157f1a76cbcf5a523601/spatial/src/spatial/gdal/file_handler.cpp#L274) rather than how it used to [set the `GdalFileHandler` as the default handler](https://github.com/Maxxen/duckdb_spatial/blob/d0d35f96b7398941c56f64714171bb3bc4f04963/spatial/src/spatial/gdal/file_handler.cpp#L253) means that other VSI handlers no longer are processed before the Duckdb FileHandler. So when it [opens the file its still prefixed with `/vsigzip/` and fails](https://github.com/duckdb/duckdb_spatial/pull/187/files#diff-7c89e70e2a84977f05337b4d51ffcb70777bd5bb6e6eb476ca99ed69f2160c18L253). @Maxxen does that sound right?

**Comment by Maxxen** [comment]
Yes that sounds right, but in theory you should be able to chain filesystems, so im guessing we probably just need to change how/where we insert the duckdb prefix. But i havent looked in to it in detail yet.

**Comment by mick** [comment]
> should be able to chain filesystems

Yeah, looking how the [gzip VSI works](https://github.com/OSGeo/gdal/blob/48ddaf28db2826c635243abd469e7c7d2e749bdc/port/cpl_vsil_gzip.cpp#L2963-L2982) maybe if the duckdb FileSystem fails to open the file, fallback to `VSIFilesystemHandler` to see if it can resolve the file and possibly other chained VSIs.
