### ISSUE TITLE
Any plans to add geometric style control arguments? 

### ISSUE THREAD

**Issue by benerain** [duckdb/duckdb_spatial#264]
For example, when I use the buffer function, I want to be able to control the style of the end caps and joins of the resulting buffer. Specifically, I want to be able to set the end cap style to ROUND, BEVEL, or SQUARE, and the join style to ROUND, MITER, or BEVEL. How can I do this in DuckDB? or Is there a workaround for this?

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this suggestion!
Yes, this doesn't seem like it would be too hard to do, we just need to add another parameter to st_buffer. I will see if I can sneak it in in the next PR I make.

**Comment by Youssef-Harby** [comment]
Any updates on this ? @Maxxen

**Comment by Maxxen** [comment]
@Youssef-Harby implemented in #271
