### ISSUE TITLE
Export duckdb table to gpkg format is throwing error duckdb version: 0.10.0  and python version: 3.12.2 in conda environment

### ISSUE THREAD

**Issue by GuntuAshok** [duckdb/duckdb_spatial#283]
---------------------------------------------------------------------------
CatalogException                          Traceback (most recent call last)
Cell In[9], [line 1](vscode-notebook-cell:?execution_count=9&line=1)
----> [1](vscode-notebook-cell:?execution_count=9&line=1) con.sql("COPY stream TO 'streams.gpkg' WITH (FORMAT GDAL, DRIVER 'GPKG')")

CatalogException: Catalog Error: Copy Function with name gdal does not exist!
Did you mean "csv"?

python version: 3.12.2 in conda environment
duckdb version: 0.10.0
OS: Windows 11
I'm unable to install duckdb via conda-forge so installed duckdb via pip in my conda environment.

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue. Have you made sure the spatial extension is installed and loaded?

**Comment by GuntuAshok** [comment]
yes I executed
con.install_extension("spatial")
con.load_extension("spatial")

**Comment by GuntuAshok** [comment]
Tested the same database with duckdb CLI version 0.10.0 and this same command worked as expected.
COPY stream TO 'streams.gpkg' WITH (FORMAT GDAL, DRIVER 'GPKG')

**Comment by GuntuAshok** [comment]
Okay I figured out what went wrong. Problem is with my code, and I sorted it out.
