### ISSUE TITLE
Geometry Polygon::CreateFromBox has a typo in v0.10.2 branch

### ISSUE THREAD

**Issue by ahuarte47** [duckdb/duckdb_spatial#312]
https://github.com/duckdb/duckdb_spatial/blob/a62e73ce80db4e136bd169535e2687909fbb048a/spatial/include/spatial/core/geometry/geometry.hpp#L800

I think this should be:

`LineString::SetVertex(ring, 1, {minx, maxy});`

**Comment by Maxxen** [comment]
Thanks! Good catch! I've pushed a fix for it.

**Comment by ahuarte47** [comment]
I am closing, fix merged. Thanks @Maxxen
