### ISSUE TITLE
I don't find how to set a SRID(epsg) in wkb?

### ISSUE THREAD

**Issue by automataIA** [duckdb/duckdb_spatial#336]
How to set a SRID(epsg) in wkb? 
with postgis I use ST_SRID.

**Comment by Maxxen** [comment]
Hi! This is currently not possible. DuckDB spatial does not store SRID's inside the geometry values themselves. Also, ISO-standard WKB does not support storing SRID's either, only the _extended_ (E)WKB flavor does. 

However, we could maybe in the future look into enabling the creation of EWKB's from `WKB_BLOB`s that can take an additional SRID argument.
