### ISSUE TITLE
remove extensions

### ISSUE THREAD

**Issue by geometa** [duckdb/duckdb_spatial#346]
how to remove spatial extensions

**Comment by geometa** [comment]
The old version of the plug-in was installed. When I wanted to install the new version of the plug-in, I deleted the plug-in file under the .duckdb folder. When installing the new plug-in, it will prompt that the plug-in already exists. Finally, I manually downloaded the new version of the plug-in and manually created the corresponding folder, the installation is successful.

**Comment by carlopi** [comment]
```
FORCE INSTALL spatial [FROM nightly];
```
will override whatever was present locally.
