### ISSUE TITLE
Not implemented Error: WKB Reader: Geometry type 11 not supported

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb_spatial#365]
I'm using ``v0.10.2 1601d94f94``.

```sql
select * from st_read('GHUB2018.gpkg') LIMIT 1;
```

```
Not implemented Error: WKB Reader: Geometry type 11 not supported
```

It's the GPKG inside the of the RAR download from here: https://zenodo.org/records/5168383

Any way to ignore the geometry at least if it can't be implemented?

**Comment by marklit** [comment]
As a workaround, I tried treating the GPKG file as a SQLite3 database but DuckDB isn't happy with the way the geom field is structured. QGIS can open this file without issue through.

```sql
D ATTACH 'GHUB2018.gpkg' AS ghub;
D USE ghub;
D .schema --indent
```

```sql
CREATE TABLE UE_2018(
  fid BIGINT PRIMARY KEY,
  geom VARCHAR,
  UE_Area DOUBLE,
  CONTINENT VARCHAR,
  Country VARCHAR
);;
```

```sql
D SELECT * FROM UE_2018 LIMIT 1;3
```

```
Mismatch Type Error: Invalid type in column "geom": column was declared as text, found "GP" of type "blob" instead.
```

```sql
SELECT * EXCLUDE(geom) FROM UE_2018 LIMIT 1;
```

```
┌───────┬────────────────────┬───────────┬─────────────┐
│  fid  │      UE_Area       │ CONTINENT │   Country   │
│ int64 │       double       │  varchar  │   varchar   │
├───────┼────────────────────┼───────────┼─────────────┤
│     1 │ 485.43857826704914 │ Oceania   │ New Zealand │
└───────┴────────────────────┴───────────┴─────────────┘
```

```sql
D SELECT * EXCLUDE(geom), geom::BLOB FROM UE_2018 LIMIT 1;
```

```
Mismatch Type Error: Invalid type in column "geom": column was declared as text, found "GP" of type "blob" instead.
```

```sql
SELECT * EXCLUDE(geom), geom::TEXT FROM UE_2018 LIMIT 1;
```

```
Mismatch Type Error: Invalid type in column "geom": column was declared as text, found "GP" of type "blob" instead.
```

**Comment by Konkrad** [comment]
I have a similar problem:
>  WKB type '942747698' is not a supported geometry type

(and many other types)

when trying to converting a csv to geoparquet with the nightly build of duckdb. 

What makes me a bit suspicious is that I create geometries like this:

```
copy (select *, ST_Point(LON, LAT) as geometry from read_csv('input.csv',PARALLEL=TRUE)) 
```

It seems not to be related to the geometry column as I don't have any error when I exclude all the others. The more columns I excluded from the CSV the likelier was it that I ran without a problem.

**Comment by Maxxen** [comment]
@marklit 

It seems like the file contains curve geometries, which DuckDB does not support.
You can work around this by having `st_read` output the raw WKB (without converting it to GEOMETRY) by passing the optional `keep_wkb = TRUE` argument to it. 

You should then be able to convert the WKB column into GEOMETRY with a `TRY_CAST` to have the unsupported geometries (all failed casts) turn to NULL.

**Comment by Maxxen** [comment]
@Konkrad 

It seems like you have an unrelated issue but I don't really understand what you mean. Could you share exactly what you are trying to do, the full SQL and ideally a dataset that reproduces the issue?

**Comment by marklit** [comment]
I'll leave this here to help anyone else who has unsupported geometry. This will allow you to exclude the records that aren't supported and work with the ones that are.

```sql
select substr(geom::BLOB::TEXT, 0, 16) as geom_type_str,
       count(*)
from st_read('GHUB2018.gpkg', keep_wkb=TRUE)
group by 1;
```

```
┌─────────────────┬──────────────┐
│  geom_type_str  │ count_star() │
│     varchar     │    int64     │
├─────────────────┼──────────────┤
│ \x01\x0C\x00\x0 │           72 │
│ \x01\x06\x00\x0 │        10170 │
└─────────────────┴──────────────┘
```

The 10K ``\x01\x06\x00\x0`` records are MULTIPOLYGONs and are fine. Below I've excluded the `\x01\x0C\x00\x0` is the curve geometry in the WHERE clause which stops these records from being interpreted by the Spatial Extension.

```sql
select ST_GeometryType(geom::GEOMETRY) as geom_type,
       count(*)
from st_read('GHUB2018.gpkg', keep_wkb=TRUE) 
WHERE substr(geom::BLOB::TEXT, 0, 16) != '\x01\x0C\x00\x0' 
group by 1;
```

```
┌───────────────┬──────────────┐
│   geom_type   │ count_star() │
│ geometry_type │    int64     │
├───────────────┼──────────────┤
│ MULTIPOLYGON  │        10170 │
└───────────────┴──────────────┘
```

**Comment by cvargas-xbrein** [comment]
FROM country_mx_view_blocks
WHERE ST_INTERSECTS(
    shape , 
    ST_GeomFromWKB( CAST('{ POINT_WKT}'AS BINARY)) 
)
GROUP BY
  administrative_area_level_2,
  administrative_area_level_3,
  income_level,
  recoba_id;

NotImplementedException: Not implemented Error: WKB Reader: Geometry type 22 not supported

**Comment by marklit** [comment]
@Maxxen is there a way that geometry outside of the 7 supported types could somehow be dumped to WKT with a helper function? It could at least give people a clue as to what sorts of shapes they're dealing with and give them a chance to look around for ways of converting those shapes into linestrings or another shape that is compatible with GEOS.

I had a case recently where I was dealing with POLYGON Z shapes and all that was needed was converting it back into POLYGON fixed the issue.

I've just spent 10 minutes looking around PostGIS' source code for what shape number 22 might be and I can't find it. The GIS world will forever require working with outside data as it's not often cost-effective for everyone to go and collect their own data.

**Comment by Maxxen** [comment]
@marklit DuckDB spatial has supported `POLYGON Z` (and M!) for more than a year at this point, so that sounds like something else is going wrong. 

In general, because `WKB_BLOB` is castable to `GEOMETRY` you can use the `TRY_CAST` sql operator to attempt a cast to another type, and return NULL for failed conversions. E.g. the following should work to ignore unsupported WKB types.

```
SELECT TRY_CAST(wkb_geometry AS GEOMETRY) FROM st_read('some_dataset.fgb', keep_wkb := true);
```


>is there a way that geometry outside of the 7 supported types could somehow be dumped to WKT with a helper function?

That's not a terrible idea, it might be hard to come up with a complete exhaustive list or figure out how to print the rest of the data to WKT but we could at least come up with a suggestion if conversion fails.

**Comment by marklit** [comment]
How about adding a fall-back in ``ST_GeometryType`` to at least print the type and add in as many types as possible? I think it was PostGIS where EWKB originated and took off so there might be somewhere in that codebase with a bigger list than what I've found so far.

**Comment by Maxxen** [comment]
`ST_GeometryType` works on `GEOMETRY`, which is already converted to our internal format. But we could add a overload for WKB_BLOB.

**Comment by cvargas-xbrein** [comment]
> FROM country_mx_view_blocks WHERE ST_INTERSECTS( shape , ST_GeomFromWKB( CAST('{ POINT_WKT}'AS BINARY)) ) GROUP BY administrative_area_level_2, administrative_area_level_3, income_level, recoba_id;
> 
> NotImplementedException: Not implemented Error: WKB Reader: Geometry type 22 not supported

Well was my bad only use a ST_GeomFroText('{POIN_.WKT}' ) AND WORKS

**Comment by cboettig** [comment]
Still seeing this error even when using the `TRY_CAST` approach with a gdb package ([this one from USGS](https://doi.org/10.5066/P96WBCHS)).

```
SELECT TRY_CAST(wkb_geometry AS GEOMETRY) FROM st_read('some_dataset.gdb', keep_wkb := true);
```

Reading the layer in with geopandas+pygrio and back out as an fgb first lets me  work around it but feels like a poor hack.  Would be great to figure this out, then maybe can also get this implemented as a fallback option in `ibis.read_geo()` so we are closer to matching geopandas?
