### ISSUE TITLE
GPKG: Not implemented Error: Multiple geometry fields not supported yet

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb_spatial#366]
Any change support for multiple geom fields in GPKG could get added? Natural Earth has multiple bounding boxes and centroids for populated places around the world.

```sql
COPY (
    SELECT NAME_EN,
           ADM0CAP::BOOL AS is_capital,
           MEGACITY::BOOL as is_mega_city,
           ST_Extent(('LINESTRING(' ||
                                  MAX_BBXMIN || ' ' ||
                                  MAX_BBYMIN || ', ' ||
                                  MAX_BBXMAX || ' ' ||
                                  MAX_BBYMAX || ')')::GEOMETRY)::GEOMETRY as bbox_max,
           ST_CENTROID(ST_POINT(LONGITUDE, LATITUDE)) as centroid
    FROM st_read('ne_10m_populated_places.shx')
) TO 'bboxes.gpkg'
    WITH (FORMAT GDAL,
          DRIVER 'GPKG',
          LAYER_CREATION_OPTIONS 'WRITE_BBOX=YES');
```

Not implemented Error: Multiple geometry fields not supported yet

**Comment by rouault** [comment]
> Any change support for multiple geom fields in GPKG could get added?

no, that can't be implemented for GeoPackage. The GeoPackage format doesn't support multiple geometry fields per layer.

**Comment by marklit** [comment]
I could only see polygons in the source file though. I'll pick the GPKG file apart with sqlite3 when I'm back at my desk.

**Comment by marklit** [comment]
Ah, okay. Understood.
