### ISSUE TITLE
BOX_2D to POLYGON support on the way any time soon?

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb_spatial#369]
GPKG doesn't support BOX_2D and plenty of other things fight with it. The syntax for building bounding boxes with it is really clean. It would be great if I could cast them to a POLYGON.

**Comment by Maxxen** [comment]
Hi! You should be able to cast it i to a geometry already with ::GEOMETRY, which you can in turn cast to polygon_2d

**Comment by marklit** [comment]
I can, thanks for that.
