### ISSUE TITLE
How to export a table as full GeoJSON document?

### ISSUE THREAD

**Issue by DrewScatterday** [duckdb/duckdb_spatial#370]
I opened a question on [stackoverflow](https://stackoverflow.com/questions/78832305/duckdb-constructing-a-full-geojson-feature-collection) and asked a discussion question [on the main repo](https://github.com/duckdb/duckdb/discussions/13289#discussion-7007797) but figured I'd post here too for visibility 

The documentation for [St_AsGeoJSON](https://github.com/duckdb/duckdb_spatial/blob/main/docs/functions.md#st_asgeojson) states "This does not return a complete GeoJSON document, only the geometry fragment. To construct a complete GeoJSON document or feature, look into using the DuckDB JSON extension in conjunction with this function." I'm having a hard time figuring out how to do that

I want to return my entire table as an array of geojson objects. I'd like to add a `properties` key where each of my tables column values are included in it. Do I need to specify every column name manually or can I do this dynamically since its just `column name: value`. What is the best way to accomplish this? 

Example: 
```json 
[
       {"type" : "Feature", 
        "properties" : {  
            "capacity" : "10", 
            "type" : "U-Rack",
            "mount" : "Surface"
        }, 
        "geometry" : { 
            "type" : "Point", 
            "coordinates" : [ -71.073283, 42.417500 ] 
        }
},
       {"type" : "Feature", 
        "properties" : {  
            "capacity" : "10", 
            "type" : "U-Rack",
            "mount" : "Surface"
        }, 
        "geometry" : { 
            "type" : "Point", 
            "coordinates" : [ -71.073283, 42.417500 ] 
        }
},
]
```

**Comment by DrewScatterday** [comment]
answering my own question on stackoverflow

**Comment by DrewScatterday** [comment]
Hey no worries thanks for taking the time to answer and thanks for all your hardwork you do on duckdb!! 

Do you know if its possible to include all columns dynamically with `*`? 

But I ended up just returning the rows from the query and converting it to geojson with a code function which worked pretty quick even on larger queries

**Comment by tbbuck** [comment]
In case someone finds it useful, this is how I'm grabbing a single FeatureCollection GeoJSON object from a given feature set:

```sql
LOAD spatial;
LOAD h3;

SELECT CAST( { -- build the FeatureCollection
    type: 'FeatureCollection', 
    features: json_group_array( CAST( {  -- build individual feature
        type: 'Feature', 
        geometry: ST_AsGeoJSON( my_geometry ), -- the column name of the geometry  
        properties: { 
            exampleToKeepH3CellId : h3_cell_id  -- example property, can put anything here
        } 
    } AS JSON) ) 
} AS JSON) as my_feature_collection -- done! You can use any SQL FROM statement below
FROM (  
    -- generate test boundaries using a point's surrounding H3 grid disk
    SELECT h3_cell_ids.h3_cell_id, ST_GeomFromText( h3_cell_to_boundary_wkt( h3_cell_ids.h3_cell_id ) ) as my_geometry FROM (  SELECT UNNEST( h3_grid_disk( h3_latlng_to_cell(51.501476, -0.140634, 10), 10) ) AS h3_cell_id ) h3_cell_ids 
) h3_cell_boundaries;

```

If someone has found a better way - or can see some improvement(s) to this - please let me know!

**Comment by rory-orennia** [comment]
@tbbuck I found that using GDAL can do this for you (except a couple un-implemented column types that you can work around https://github.com/duckdb/duckdb-spatial/issues/468 https://github.com/duckdb/duckdb-spatial/issues/479) if you're exporting to a file:
```SQL
COPY (
  -- Some Select Statement
  -- whatever has the name 'geometry' will go into the geometry of the Feature
  -- so you can do ST_POINT(lon, lat) or just select the column if it's already a geometry object
  -- other columns that are selected are added as properties on the Feature
) TO 'test.geojson' 
WITH (FORMAT GDAL, DRIVER 'GeoJSON', LAYER_NAME 'The Name of the FeatureCollection');
```

**Comment by tbbuck** [comment]
Oh I like that @rory-orennia , good skills!

**Comment by docentYT** [comment]
What is the best way to select features from spatial database in order to stream it via api? Streaming is necessary with huge number of features.
