### ISSUE TITLE
Consider implementation of ST_AsMVT ?

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb_spatial#374]
PostGIS has the function [ST_AsMVT](https://postgis.net/docs/ST_AsMVT.html) (and related functions for tiling, as shown in the docs) which can be useful for generating vector tiles for more efficient visualization.  Probably an involved implementation, but at least wanted to open this request as a placeholder of interest.

**Comment by Maxxen** [comment]
Discussed in #241. As soon as I land support for spatial indexes Im planning to pick this up, as once that's implemented using ST_AsMVT in practice actually becomes a feasible once you can filter and clip the source geometries to the tile bounds efficiently.

**Comment by cboettig** [comment]
sorry I missed that! perfect, will close this and keep an eye there.  exciting stuff.
