### ISSUE TITLE
doc example failed

### ISSUE THREAD

**Issue by tpolong** [duckdb/duckdb_spatial#378]
CREATE TABLE zones AS SELECT zone, LocationId, borough, ST_GeomFromWKB(wkb_geometry) AS geom
FROM st_read('./spatial/test/data/nyc_taxi/taxi_zones/taxi_zones.shx');
should be
CREATE TABLE zones AS SELECT *
FROM st_read('./spatial/test/data/nyc_taxi/taxi_zones/taxi_zones.shx');

**Comment by Maxxen** [comment]
Fixed by #401
