### ISSUE TITLE
Spherical Calculations Bug - Coordinate Transposition

### ISSUE THREAD

**Issue by jtbaker** [duckdb/duckdb_spatial#384]
I made a note of some issues with the Spherical Calculations in https://github.com/duckdb/duckdb_spatial/issues/16#issuecomment-2221171749 that were corroborated by several other uses or not, but not sure if they got noticed or not, so figured I would make a separate issue.

In short, `ST_AREA_SPHEROID` and related functions seem to have a bug with lat/lng coordinate  transposition - any coordinate with a longitude < -90 (so, the western portion of the US) returns NaN when using one of those functions.

See https://github.com/duckdb/duckdb_spatial/issues/16#issuecomment-2226391634 for a visual:
![image](https://github.com/user-attachments/assets/a0c65de5-ae54-40b9-a102-15b74e9e1aeb)

**Comment by Maxxen** [comment]
I replied in #16
