### ISSUE TITLE
`ST_GeneratePoints` and regular grid

### ISSUE THREAD

**Issue by CGenie** [duckdb/duckdb_spatial#411]
Is it possible to generate a regular grid of points in a given rectangle?

The docs (https://duckdb.org/docs/extensions/spatial/r-tree_indexes.html#example) reveal an undocumented function: `ST_GeneratePoints`:
```sql
select * from st_generatepoints({min_x: 0, min_y: 0, max_x: 100, max_y: 100}::BOX_2D, 10_000, 1337);
```
apparently returns 10k points, but I think they're random?

**Comment by Maxxen** [comment]
Yes, they are random. Im not sure why table functions aren't automatically generated by my docs generation script but I'll look into it.

That said, I don't think a special function is warranted to generate a regular grid when SQL make it so easy to do cross products anyway. E.g.

```sql
SELECT ST_Point(x,y) FROM range(0, 100, 10) as a(x), range (0, 100, 10) as b(y);
┌────────────────┐
│ st_point(x, y) │
│    geometry    │
├────────────────┤
│ POINT (0 0)    │
│ POINT (0 10)   │
│ POINT (0 20)   │
│ POINT (0 30)   │
│ POINT (0 40)   │
│      ·         │
│      ·         │
│      ·         │
│ POINT (90 50)  │
│ POINT (90 60)  │
│ POINT (90 70)  │
│ POINT (90 80)  │
│ POINT (90 90)  │
├────────────────┤
│    100 rows    │
│   (10 shown)   │
└────────────────┘
```

Hell, you could even wrap it in a table macro if you want to:

```sql
CREATE MACRO st_generategrid(min, max, step) AS TABLE 
SELECT ST_Point(x,y) 
FROM range(min, max, step) as a(x), range (min, max, step) as b(y);
```

**Comment by CGenie** [comment]
True! Thank you, I somehow didn't think of `CROSS JOIN`.
