### ISSUE TITLE
Cast ST_Point to FLOAT?

### ISSUE THREAD

**Issue by keller-mark** [duckdb/duckdb_spatial#413]
Hi, Is it possible to cast the ST_Point to use FLOAT (rather than DOUBLE)?

I have tried the following

```SQL
SELECT ST_Point(x, y)::FLOAT[2] as my_point
```

but it does not seem to work

**Comment by Maxxen** [comment]
Hello!
No, unfortunately we don't have any geometry casts to fixed size arrays, although we could look into adding that in the future eventually. Would you mind explaining what use-case you have in mind for this?

If you already have the point in a column you could do this instead:
```sql
SELECT [ST_X(point), ST_Y(point)]::FLOAT[2]
```

**Comment by keller-mark** [comment]
Thank you very much, this pointed me in the right direction. I was able to achieve the desired result with

```sql
SELECT [x, y]::FLOAT[2] AS my_point
```
