### ISSUE TITLE
`St_Distance_Sphere` produces wrong results

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb_spatial#442]
please refer to the Redshift example: https://docs.aws.amazon.com/redshift/latest/dg/ST_DistanceSphere-function.html#ST_DistanceSphere-function-examples

The DucK DB equivalent was:
```sql
WITH airports_raw ( code
                    , lon
                    , lat )
    AS (    (   SELECT  'MUC'
                        , 11.786111
                        , 48.353889 )
            UNION (
                SELECT  'FRA'
                        , 8.570556
                        , 50.033333 )
            UNION (
                SELECT  'TXL'
                        , 13.287778
                        , 52.559722 ) )
    , airports1 ( code, location )
    AS (    SELECT  code
                    , St_Point( lon, lat )
            FROM airports_raw )
    , airports2 ( code, location )
    AS (    SELECT *
            FROM airports1 )
SELECT  ( airports1.code || ' <-> ' || airports2.code ) AS airports
        , Round( St_Distance_Sphere( airports1.location, airports2.location ) / 1000, 0 ) AS distance_in_km
FROM airports1
    , airports2
WHERE airports1.code < airports2.code
ORDER BY 1
;

/* result
┌─────────────┬────────────────┐
│ airports    │ distance_in_km │
├─────────────┼────────────────┤
│ FRA <-> MUC │         400.00 │ correct 299
├─────────────┼────────────────┤
│ FRA <-> TXL │         590.00 │ correct 432
├─────────────┼────────────────┤
│ MUC <-> TXL │         486.00 │ correct 480
└─────────────┴────────────────┘
*/
```

The result is very off though, am I doing something wrong?

**Comment by tshelianthus** [comment]
I think I have found the reason for this error. #450 

When using `ST_Point`, we used the standard [longitude, latitude] order.

However, in the [`st_distance_spheroid`](https://duckdb.org/docs/extensions/spatial/functions.html#st_distance_spheroid) example, it states that "the coordinates are in WGS84 and [latitude, longitude] axis order," which clearly does not align with the standard convention.

**Comment by Maxxen** [comment]
Yes, ST_Distance_Sphere expects the axis order to be in lat/lon. I've [elaborated more on this in this thread](https://github.com/duckdb/duckdb_spatial/issues/16#issuecomment-2327011935)

**Comment by manticore-projects** [comment]
Thank you for the explanation although I find it highly confusing to switch the  standard [longitude, latitude] order (without any indication in the function name and when its impossible to derive this information from the parameters).
