### ISSUE TITLE
ST_Dimension returns wrong result

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb_spatial#443]
Greetings!
Coming from https://docs.aws.amazon.com/redshift/latest/dg/ST_NDims-function.html#ST_NDims-function-examples

DuckDB produces:
```sql
SELECT ST_Dimension(ST_GeomFromText('LINESTRING Z(0 0 3,1 1 3,2 2 3,0 0 3)')) d;

/*
┌───┐
│ d │
├───┤
│ 1 │ expected was 3
└───┘
*/
```

Am I doing something wrong here?

**Comment by Maxxen** [comment]
Hi!

Perhaps the docs could use some more love here, but this is expected. `ST_Dimension` returns the _surface dimension_ of the geometry as defined by the ogc spec/simple features model, where point/multipoint = 0, linestring/multilinestring = 1 and polygon/multipolygon = 2. This function [works the same as in PostGIS](https://postgis.net/docs/ST_Dimension.html)

We don't have `ST_NDims/ST_NDimensions` to get the number of coordinate dimension, but you can use `ST_HasZ` and `ST_HasM` to create your own macro:

```
CREATE FUNCTION ST_NDims(g) AS 2 + ST_HasZ(g::GEOMETRY)::INT + ST_HasM(g::GEOMETRY)::INT;
```

**Comment by manticore-projects** [comment]
Thank you for the explanation!
