### ISSUE TITLE
Inner-join v. cross-join with R-TREE?

### ISSUE THREAD

**Issue by JimShady** [duckdb/duckdb_spatial#466]
I would like to write this query:

Query 1:

```
            SELECT         p.* 
            FROM           portfolio p
            INNER JOIN     buildings b
            ON             ST_Within(p.geometry, b.geometry)
```

... but the performance is very slow. I do not think it is making use of the R-Tree index I created?

But this query, which is very similar, is very fast. I think it IS taking the R-Tree. Is this a bug? Am I misunderstanding things?

Query 2:

```
            SELECT       p.* 
            FROM         portfolio p, buildings b
            WHERE        ST_Within(p.geometry, b.geometry)

```

 Thanks

**Comment by Maxxen** [comment]
Hello!
As [written in the docs](https://duckdb.org/docs/extensions/spatial/r-tree_indexes#what-are-the-limitations-of-r-tree-indexes-in-duckdb)
> The R-tree index will only be used to perform "index scans" when the table is filtered (using a WHERE clause) with one of the following spatial predicate functions (as they all imply intersection): ST_Equals, ST_Intersects, ST_Touches, ST_Crosses, ST_Within, ST_Contains, ST_Overlaps, ST_Covers, ST_CoveredBy, ST_ContainsProperly.

That is, the R-Tree index is _not_ used to accelerate JOINs.

**Comment by JimShady** [comment]
Thanks @Maxxen  . I did read the docs and see that but thought that it still might apply to a join, given in this case it's kind of the same thing. I will re-write my code.

**Comment by Maxxen** [comment]
Im not sure why the cross join + is faster, I don't think it will use the R-Tree either given that neither arguments to the where clause are constant. Are you've written the queries properly/they return the equivalent results?

**Comment by JimShady** [comment]
I'll generate some test data and open a few ticket when it's ready. Thanks
